//! chat_module — a Rust Logos Module (cdylib authoring model).
//!
//! Wraps libchat for the e2e-encrypted chat protocol and reaches the network
//! via delivery_module over IPC. The module-impl C ABI (`logos_module_*`
//! exports, the `ChatModule` trait, dispatch) is generated from
//! `chat_module.lidl` by logos-lidl-gen and `include!`d below from
//! `generated/provider_gen.rs`; the matching Qt plugin glue is generated by
//! logos-module-builder. The contract consumers call is `chat_module.lidl`;
//! we implement it here.
//!
//! Thread safety. State is split across two locks (see [`module`]): the client
//! lock guards the libchat `ChatClient` (held across crypto); the display lock
//! guards the conversation history, so the read methods never wait on the slow
//! client work. The operations below are safe to call from any thread.
//!
//! `init` imposes no thread-affinity requirement: the SDK makes calls into
//! delivery_module (event subscription, publish) thread-safe regardless of the
//! caller's thread.
//!
//! Return conventions. Status-bearing methods return `result`, surfaced here as
//! `Result<serde_json::Value, String>`: `Ok(value)` carries any payload (a
//! conversation id or `Null`), `Err(message)` a human-readable reason.
//! Collection getters return `serde_json::Value` (a JSON array/object);
//! `get_installation_name`/`get_address`/`get_log_path` return a plain string,
//! empty when not initialised.
//!
//! Events reach consumers over the lp_* IPC channel: the operations below call
//! the generated `emit_*` functions (see the included scaffold), which the host
//! marshals onto the Qt thread and republishes as IPC events.
//!
//! Security. The identity store opened by `init` is keyed from the
//! host-assigned instance persistence path: obfuscated, not protected.
//! Passphrase UX is planned.

mod actions;
mod delivery;
mod inbound;
mod logging;
mod module;
mod panic_hook;
mod persistence;

use serde_json::Value;

use module::{module, InstallOutcome};

// The module-impl C ABI scaffold generated from chat_module.lidl: the
// `ChatModule` trait, `RustModuleContext`, `install`, dispatch, the `emit_*`
// event emitters, and the `#[no_mangle] logos_module_*` exports the Qt glue
// drives. Machine output — not hand-maintained — so it lives in its own module
// that opts out of clippy and rustc lints; we lint the module code, not this.
// (`include!` already keeps it out of rustfmt, which does not descend into it.)
mod generated {
    #![allow(warnings)]
    #![allow(clippy::all)]
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/generated/provider_gen.rs"
    ));
}
pub(crate) use generated::*;

/// Error string for the unreachable lock-poison case. The process runs under
/// `panic = "abort"`, so a panic dies before it can poison the mutex; the arm
/// exists only to satisfy the `result` return type.
const ERR_LOCK_POISONED: &str = "internal error: module lock poisoned";

/// The delivery network joined when `init`'s config names none.
const DEFAULT_DELIVERY_PRESET: &str = "logos.test";

/// The delivery preset `config` selects, or [`DEFAULT_DELIVERY_PRESET`].
///
/// An absent field and an empty one are the same "unset": every `ChatConfig`
/// field is optional, and a caller sending `""` means no more than one omitting
/// the key. Decoding the record itself is the SDK's job now that the parameter
/// is typed — this is only the defaulting.
fn delivery_preset(config: &ChatConfig) -> &str {
    match config.delivery_preset.as_deref() {
        None | Some("") => DEFAULT_DELIVERY_PRESET,
        Some(named) => named,
    }
}

/// The `ChatModule` contract implementation. Stateless: all module state lives
/// in the [`module`] singleton and the display lock, so every method delegates
/// to `actions` (which own their locking) and `&mut self` is unused.
#[derive(Default)]
struct ChatModuleImpl;

impl ChatModule for ChatModuleImpl {
    fn init(&mut self, config: ChatConfig) -> Result<Value, String> {
        panic_hook::install_once();
        logging::install_once(config.log_level.as_deref().unwrap_or_default());

        let preset = delivery_preset(&config);

        match module().install_with(actions::initialize) {
            Err(_) => Err(ERR_LOCK_POISONED.to_string()),
            Ok(Ok(InstallOutcome::Installed)) => {
                tracing::info!("init: state installed, joining delivery preset {preset}");
                // State is installed and the module lock is released; only now
                // bootstrap delivery, so its async completion callbacks acquire
                // a free lock instead of re-entering the one init holds.
                actions::start_delivery_bootstrap(preset);
                Ok(Value::Null)
            }
            Ok(Ok(InstallOutcome::AlreadyInstalled)) => {
                tracing::warn!(
                    "init: already initialised; any new arguments are ignored, \
                     call shutdown() first to reconfigure"
                );
                Ok(Value::Null)
            }
            Ok(Err(e)) => {
                tracing::error!("init: {e}");
                Err(e.to_string())
            }
        }
    }

    fn shutdown(&mut self) -> Result<Value, String> {
        // Take the module out of the lock before joining the inbound thread —
        // the worker may try to re-acquire the mutex to handle a pending event,
        // and holding it during `join` would deadlock.
        let taken = module().take().map_err(|_| ERR_LOCK_POISONED.to_string())?;
        if let Some(ms) = taken {
            actions::shutdown(ms);
        }
        Ok(Value::Null)
    }

    fn get_log_path(&mut self) -> String {
        logging::log_path()
    }

    /// Touches no state and takes no lock: a probe that could block would report
    /// a busy module as a dead one, and the process answering is the whole
    /// answer. Deliberately silent, since a caller polls this.
    fn health(&mut self) -> bool {
        true
    }

    fn get_installation_name(&mut self) -> String {
        actions::installation_name()
    }

    fn set_installation_name(&mut self, name: String) -> Result<Value, String> {
        actions::set_installation_name(&name)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn get_address(&mut self) -> String {
        actions::get_address()
    }

    fn create_conversation(&mut self, peer_address: String) -> Result<Value, String> {
        actions::create_conversation(&peer_address)
            .map(Value::String)
            .map_err(|e| e.to_string())
    }

    fn create_group_conversation(&mut self, name: String, desc: String) -> Result<Value, String> {
        actions::create_group_conversation(&name, &desc)
            .map(Value::String)
            .map_err(|e| e.to_string())
    }

    fn add_group_member(
        &mut self,
        convo_id: String,
        peer_address: String,
    ) -> Result<Value, String> {
        actions::add_group_member(&convo_id, &peer_address)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn list_conversations(&mut self) -> Vec<Conversation> {
        actions::list_conversations()
    }

    fn get_messages(&mut self, convo_id: String) -> Vec<Message> {
        actions::get_messages(&convo_id)
    }

    fn list_group_members(&mut self, convo_id: String) -> Vec<GroupMember> {
        actions::list_group_members(&convo_id)
    }

    fn send_message(&mut self, convo_id: String, content: String) -> Result<Value, String> {
        actions::send_message(&convo_id, &content)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn set_conversation_nickname(
        &mut self,
        convo_id: String,
        nickname: String,
    ) -> Result<Value, String> {
        actions::set_conversation_nickname(&convo_id, &nickname)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn delete_conversation(&mut self, convo_id: String) -> Result<Value, String> {
        actions::delete_conversation(&convo_id)
            .map(|()| Value::Null)
            .map_err(|e| e.to_string())
    }

    fn status(&mut self) -> Status {
        actions::status()
    }
}

/// Install hook resolved by the generated scaffold (invoked lazily on first
/// dispatch); wires `ChatModuleImpl` as the module implementation.
#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<ChatModuleImpl>();
}

#[cfg(test)]
mod tests {
    use super::*;

    // The suite that stood here covered `chat_config`/`config_field`: reading a
    // `ChatConfig` out of an untyped `Value`, whether it arrived as an object,
    // as its JSON *text* (all `logoscore call` could send), or as something that
    // was no record at all. `init` takes a typed `ChatConfig` now, so decoding —
    // and every one of those cases — belongs to the SDK, and those tests went
    // with the code they covered. The defaulting below is what is still ours.

    /// A named preset is what the caller asked for.
    #[test]
    fn a_named_preset_is_used() {
        let config = ChatConfig {
            delivery_preset: Some("logos.staging".to_string()),
            log_level: None,
        };

        assert_eq!(delivery_preset(&config), "logos.staging");
    }

    /// Every `ChatConfig` field is optional, so a caller may set only the log
    /// level and still join the default network.
    #[test]
    fn an_absent_preset_takes_the_default() {
        let config = ChatConfig {
            delivery_preset: None,
            log_level: Some("trace".to_string()),
        };

        assert_eq!(delivery_preset(&config), DEFAULT_DELIVERY_PRESET);
    }

    /// An empty preset is "unset", not a network named "". The alternative is
    /// joining nothing in silence.
    #[test]
    fn an_empty_preset_takes_the_default() {
        let config = ChatConfig {
            delivery_preset: Some(String::new()),
            log_level: None,
        };

        assert_eq!(delivery_preset(&config), DEFAULT_DELIVERY_PRESET);
    }
}
